uber/react-vis

- src/lib/utils/scales-utils.js
Custom values (e.g. color={someColor}) for scales did not work well. The problem was hidden in the linear scale that could not return a function for string values. Now the issue is fixed by using `category` scale instead.
@uber-common/data-visualization , please review.
> Fix custom values for scales.

- .eslintrc
- src/example/plot/complex-chart.js
- src/index.js
- src/lib/plot/series/abstract-series.js
- src/lib/plot/series/area-series.js
- src/lib/plot/series/bar-series.js
- src/lib/plot/series/heatmap-series.js
- src/lib/plot/series/horizontal-bar-series.js
- src/lib/plot/series/line-mark-series.js
- src/lib/plot/series/line-series.js
- src/lib/plot/series/mark-series.js
- src/lib/plot/series/vertical-bar-series.js
- src/lib/plot/xy-plot.js
- src/lib/utils/data-utils.js
- src/lib/utils/scales-utils.js
This update does following things:
- Changes the way how the series' flags are passed to the parent (`isDomainAdjustmentNeeded` is moved to `getParentConfig` function). 
- Automatically adds zero to the domain if the series requires that (through zeroBaseValue parent config; see #13 for more detail).
- Replaces existing `BarSeries` with `VerticalBarSeries` and `HorizontalBarSeries` in order to simplify the code.
@uber-common/data-visualization please take a look.
> Add zero to bar chart; align bar items to 0

- src/example/plot/static-hints.js
- src/lib/plot/hint.js
Removing offsets for hints entirely: we don't need them on the chart. The changes can be made with CSS.
This change will solve #14.
@uber-common/data-visualization, please review.
> Remove offsetLeft/offsetTop entirely.

- src/lib/make-vis-flexible.js
- src/lib/plot/axis.js
- src/lib/plot/crosshair.js
- src/lib/plot/grid-lines.js
- src/lib/plot/hint.js
- src/lib/plot/horizontal-grid-lines.js
- src/lib/plot/series/area-series.js
- src/lib/plot/series/bar-series.js
- src/lib/plot/series/heatmap-series.js
- src/lib/plot/series/horizontal-bar-series.js
- src/lib/plot/series/line-mark-series.js
- src/lib/plot/series/line-series.js
- src/lib/plot/series/mark-series.js
- src/lib/plot/series/vertical-bar-series.js
- src/lib/plot/vertical-grid-lines.js
- src/lib/plot/x-axis.js
- src/lib/plot/xy-plot.js
- src/lib/plot/y-axis.js
- src/lib/radial-chart/radial-chart.js
- src/lib/table/table.js
- src/lib/treemap/treemap.js
`static get displayName` produces breaking interference with livereactload. Currently `displayName` property is attached to the class after the class is created.
**Note: This should be changed in future, when static properties will come out of the Babel's stage-0**
@uber-common/data-visualization , please take a look.
> Avoid using static getters for displayName.

- docs/radial-chart.md
The links within the RadialChart docs were 404ing, fixed to point to the correct doc.
> Fixed broken links in RadialChart documentation

- src/lib/plot/series/abstract-series.js
- src/lib/plot/series/area-series.js
- src/lib/plot/series/bar-series.js
- src/lib/plot/xy-plot.js
- src/lib/utils/scales-utils.js
- src/lib/utils/series-utils.js
- Add the getAttr0Value to all series: it tries to retrieve the data from [attr]0 property if given property is defined and fall back to baseValue if no property is available.
- Add the proper support of [attr]0 for the area and bar charts (not required for the rest of the series).
- Add the functionality to turn off grouping for bar charts if stacking is enabled.
Tests will follow in the next diff.
@uber-common/data-visualization , please take a look
> Enable stacking for area and bar charts

- src/lib/utils/scales-utils.js
0 height bars were caused not by the incorrect calculation of height, but by the wrong calculation of the bar width, when distance NaN instead of a real number. This small change fixes the calculation of distance (e.g. bar width) for the case when the first distance is the shortest.
This pull request fixes #40 .
@uber-common/data-visualization , please review.
> Fix 0 height bars

- src/lib/utils/react-utils.js
Hey there!
I've been testing `react@15` (which came out today) with my project, seems like everything works fine apart from the version detection in `react-utils.js` which doesn't cater to the fact that `react` is now using major versions.
This PR fixes the above issue - have smoke tested and seems to be running fine with `react@15` and `react@0.14.x`
Thanks!
> Adjust version detection to support react@15

- package.json
- src/lib/utils/scales-utils.js
In case if only 1 value existed in the chart, the ordinal scale wasn't rendered properly: the calculation of the distance between the chart's columns was broken. This fix adds an additional check for the domain: if the chart has only one value, uses the entire range is used as a distance.
Please check #49 for reference.
@uber-common/data-visualization , please take a look.
> Fix the category chart when only one value exists

- src/lib/treemap/treemap.js
- src/lib/utils/react-utils.js
- Supported `color` and `opacity` scale for the treemap.
- Performed some code cleanup: removed useless `_c` function, `defaultProps` were added, etc.
Also solves the problem of #51
> Ability to use colorRange and opacityRange for the treemap

- src/lib/plot/xy-plot.js
This fix adds the support of React.Children.toArray() into the initialization of `XYPlot` component.
This PR fixes #54.
@uber-common/data-visualization , please take a look
> Fix failures on nested arrays of children

- README.md
It was pointing to a uber-common organization
> Update broken link for Travis badge

- src/lib/radial-chart/radial-chart.js
This change fixes the opacity for the radial chart: previously the scale was not generated properly.
This pull request fixes #58.
> Fix opacity for radial chart

- src/lib/utils/scales-utils.js
- src/test/scales-utils.js
This causes weird artifacts such as the chart resizing itself on re-render if the same config object is used on each render.
Fixes #65
> Fix scale-utils mutating passed domain

- src/lib/utils/scales-utils.js
- src/test/scales-utils.js
The bar series distance calculation should calculate the minimum distance between the points, and use that to create bars that don't overlap.
- Add failing test cases
Fixes #68
> Fix bar series distance calculation

- src/lib/plot/xy-plot.js
- src/lib/radial-chart/radial-chart.js
Further investigation showed that the precalculated data was picked up from the wrong index in the data array.
This PR fixes #72 and #62
> Dont wrap data prop

- package.json
- src/lib/plot/axis.js
- src/lib/plot/grid-lines.js
- src/lib/plot/series/abstract-series.js
- src/lib/plot/series/area-series.js
- src/lib/plot/series/bar-series.js
- src/lib/plot/series/heatmap-series.js
- src/lib/plot/series/line-series.js
- src/lib/plot/series/mark-series.js
- src/lib/radial-chart/radial-chart.js
- src/lib/treemap/treemap.js
- src/lib/utils/animation-utils.js
- src/lib/utils/axis-utils.js
- src/lib/utils/scales-utils.js
- src/styles/plot.scss
This PR upgrades the library to d3@4.0. Currently all use of old version is eliminated, all the tests are passing, however, there might be some issues related to the new library.
Several things require some additional attention (but work though):
- Axes and treemaps are implemented very differently in the new d3 (new API, new tiling).
- Transitions are weird: they are adding themselves to `d3.selection`'s prototype. It might produce interesting side-effects in future.
- Some parts of d3, that are currently used, can be eliminated. For instance, `d3-collection` might be replaced with something less heavyweight since only sets are used.
This issue fixes #29 
@chrisirhc, @jckr, @mcnuttandrew, please take a look.
> Upgrade to modular d3@4.0

- src/example/main.scss
- src/main.scss
- src/styles/plot.scss
- src/styles/treemap.scss
Previous decision of having external custom fonts in the library was questionable. External fonts are removed from the library and applied in examples only. The user may define his own fonts in the body of the document and the fonts will be picked up well.
This PR fixes #82
> Eliminate the use of external fonts for the library

- package.json
- src/test/components.js
- Switched to enzyme for testing: the library provides much more functionality and helps to write simpler tests.
- Made big cleanup/refactoring in tests, fixed some incomplete props.
> Switch to enzyme for testing react components

- src/lib/make-vis-flexible.js
In a somewhat un-scientific test on my local machine, I saw a 50% reduction in latency when you have 4-5 flexible components.
I think we should discuss this a bit before merging, but here's the basic idea:
Rather than have each instance add an event listener to the window, we consolidate the subscripting into a global queue. This also means that we only have one debounce-er for the event as well.
The same idea should be applicable to anywhere that a component uses `componentDidMount` and `componentWillUnmount` to add event listeners.
The current implementation introduces a couple extra helpers. I think we can simplify this since `react-vis` only needs this pattern in one place.
**Another note:** this change removes the possibility for setting the debounce for resize on a per-component …
> Performance: only add one resize listener with makeVisFlexible

- src/lib/plot/series/abstract-series.js
- src/lib/plot/series/area-series.js
- src/lib/plot/series/bar-series.js
- src/lib/plot/series/heatmap-series.js
- src/lib/plot/series/line-series.js
- src/lib/plot/series/mark-series.js
- Click handler was added to the series.
- All event listeners are moved to AbstractSeries to avoid code duplication.
- Event listeners for area series are fixed (didn't work previously).
This PR fixes #81 and also a freshly found bug (no mouse interactions with area series work)
> Event listeners for the series

- docs/scales-and-data.md
- src/lib/utils/scales-utils.js
Tested locally by modifying `src/example/plot/time-chart.js` to use `time-utc`.
> Add time-utc scale, similar to d3.time.scale.utc

- src/lib/plot/xy-plot.js
- src/test/index.js
- src/test/xy-plot.js
Previously, stacked charts weren't rendering correctly as the
stacked data wasn't set correctly on series children.
Regression from #75 .
- Add testing for stacked bar data
> Fix stacked chart rendering

- src/lib/utils/scales-utils.js
Ordinal scales don't support `.rangePoints()` method anymore, this functionality was moved to the new `scalePoint()` scale. This fix returns the previous behavior.
We should consider renaming scale type `ordinal` to something else: currently `ordinal` scale type is not an ordinal scale anymore.
> Fix ordinal scales for d3 4.0

- docs/xy-plot.md
The values in `xy-plot.md` are now consistent with the `defaultProps` of [`xy-plot.js:70`](https://github.com/uber/react-vis/blob/master/src/lib/plot/xy-plot.js#L70).
> Corrected documented default margin to be consistent with source

- docs/treemap.md
Specify Treemap width in the example. Solved "Warning: Failed propType: Required prop `width` was not specified in `Treemap`. Check the render method of `App`".
> refine treemap doc

- src/lib/make-vis-flexible.js
remove redundant param from removeSubscriber() function, it breaks the removeSubscriber function.
So when the componentWillUnmount, the subscriber actually not remove the callback from the subscriber.
Fixing issue: https://github.com/uber/react-vis/issues/118
> fix make-vis-flexible

- src/lib/plot/axis/axis-ticks.js
Previously the axis values were duplicated due to the bad formatting of the labels ('1, 1, 2, 2' were shown instead of '1, 1.5, 2, 2.5'). This change adds a missing parameter to the format funciton and fixes this issue
> Fix the duplicate axis values

- src/example/plot/width-height-margin.js
- src/lib/plot/xy-plot.js
- src/lib/radial-chart/radial-chart.js
- src/lib/utils/chart-utils.js
- Now you no longer need to pass an object with all sides (e.g. `left`, `right`, `top` and `bottom`): partial objects such as `{left: 1000}` are accepted.
- The defaults are applied on top of the margins.
- The user is allowed to pass a number for all margins instead of an object (will be applied to all sides).
> Allow the user to apply margin as a single value or as a partial object

- src/example/radial-chart/simple-radial-chart.js
- src/lib/plot/xy-plot.js
- src/lib/radial-chart/radial-chart.js
- src/lib/treemap/treemap.js
- src/lib/utils/scales-utils.js
- src/test/components.js
- src/test/scales-utils.js
- src/test/series-utils.js
The parent picks up the domain from all values that are being passed **and** passes this domain for the children. It helps to reduce the excessive computation of the values, eliminates the use of `_allData` array and helps to run the components separately from the parent.
> Do not recreate the domain each time when the scale is passed

- docs/legends.md
- docs/xy-plot.md
- src/example/legends/discrete-color.js
- src/example/legends/searchable-discrete-color.js
- src/example/main.scss
- src/example/plot/complex-chart.js
- src/lib/legends/discrete-color-legend.js
- src/lib/legends/searchable-discrete-color-legend.js
- src/lib/plot/series/abstract-series.js
This PR makes following changes:
- Simplified the way how elements are passed into `DiscreteColorLegend`: now either objects (`title`, `color` and `disabled`) or strings (treated as titles) can be used.
- The default colors of the library are assigned as to the legends in case if no color is passed.
- The complex chart example is updated: the legend is added, the `onNearestX` is very simplified.
- A new `index` property was added into `info` object of `onNearestX(value, info)` callback (easier for the use).
Docs were updated according to these changes.
This pull request fixes #32
> Updates for DiscreteColorLegend: default colors, slight API changes, etc

- src/example/main.js
- src/example/plot/dynamic-crosshair.js
- src/example/radial-chart/donut-chart.js
- src/lib/legends/discrete-color-legend-item.js
- src/lib/legends/discrete-color-legend.js
- src/lib/radial-chart/radial-chart.js
- Added the missing donut chart example.
- Fixed the excessive `arc` generation for radial chart.
This PR fixes #83
> Donut chart example

- src/lib/plot/axis/axis.js
When orientation is set to right, the axis is not aligned properly. This change fixes #143
> Fix the misaligned Y Axis

- src/lib/plot/xy-plot.js
This change fixes the problem introduced in 0.5, when the empty scale props were treated as existing values (worked well with undefined/null before).
This PR fixes #149
> Allow the user to pass undefined and nulls as scale props

- src/index.js
This addresses part of #181. 
To reduce exposing API surface, picked only a couple of base component and utils to export.
> Expose GridLines, AxisUtils, ScaleUtils

- README.md
- docs/xy-plot.md
- src/example/plot/complex-chart.js
- src/example/plot/line-chart.js
- src/example/plot/linemark-chart.js
- src/lib/plot/series/line-series.js
In order to make smoothed line series, a user should be able to specify the name of one of the many smoothing functions that d3-shape provides: https://github.com/d3/d3-shape#curves
> Adding ability to specify d3 curve function name as a line series prop

- src/lib/utils/scales-utils.js
They are:
  getAttributeFunctor,
  getAttr0Functor,
  getAttributeValue
> Add missing 3 public functions in scales-utils.js that were not included in the original PR 181.

- src/example/plot/complex-chart.js
_formatCrosshairTitle method wasn't bound to this in the constructor. This commit fixes that.
> bound _formatCrosshairTitle with this

- src/lib/plot/hint.js
This is the set of changes to realize the new proposal for Hint that I put forward about a week ago.  
Here's the proposal in its entirety:
@chrisirhc Your comments [to clarify ORIENTATION constants](https://github.com/uber/react-vis/pull/200/files/b12458ce05c6325ad903a5dff00d4464cf2a8cf9#r92089079) and [to accept top/left/right/bottom css props to override Hint behavior ](https://github.com/uber/react-vis/pull/200/files/b12458ce05c6325ad903a5dff00d4464cf2a8cf9#r92051269) provoked me to re-think the previous [PR](https://github.com/uber/react-vis/pull/200).  This new PR would replace the previous [PR](https://github.com/uber/react-vis/pull/200).
I would like to propose the following to address and reduce your underlying concern while maintaining the original spirit of Hint orientation …
> Hint component: Deprecate orientation prop in favor of two new prop (horizontalAlign, verticalAlign)

- src/example/main.js
- src/example/main.scss
- src/example/plot/dynamic-complex-edge-hints.js
- src/example/plot/dynamic-programmatic-rightedge-hints.js
- src/example/plot/dynamic-simple-edge-hints.js
- src/example/plot/dynamic-simple-topedge-hints.js
This is the examples only portion that uses the new proposed Hint props - horizontalAlign, verticalAlign - ([PR#204](https://github.com/uber/react-vis/pull/204)) .  PR#204 contained only the change to hint.js  So, this PR is only useful if [PR#204](https://github.com/uber/react-vis/pull/204) is accepted.
Added 3 new examples to illustrate the new Hint props (see attached figure) and to serve as test of the new Hint props:
1. Dynamic Simple Edge Hints - Illustrates each point using different horizontalAlign, verticalAlign options.  The hint box includes text on which option is used.  There is no additional CSS styling. So, the example illustrates edge and quadrant placement clearly before any CSS treatment.
2. Dynamic Simple Top Edge Hints - illustrates pinning hint to top edge but using …
> Examples only for PR204 to Deprecate orientation prop in favor of two new props (horizontalAlign, verticalAlign)

- src/lib/plot/axis/axis.js
Address #221 
I am adding `defaultProps` to match the pattern of `abstract-series`
https://github.com/uber/react-vis/blob/master/src/lib/plot/series/abstract-series.js#L51-L53
> [Issue 221] Add default props class name for Axis

- src/styles/legends.scss
Position absolute already being declared.
```css
.rv-legend-titles__left,
.rv-legend-titles__right,
.rv-legend-titles__center {
position: absolute;
white-space: nowrap;
overflow: hidden;
}
```
> Remove duplicated style

- src/lib/legends/discrete-color-legend.js
Will be good to support class name append for legend
> Support classname for legend

- .eslintrc
- .gitignore
- showcase/radial-chart/custom-radius-radial-chart.js
- src/radial-chart/index.js
- src/styles/radial-chart.scss
- src/utils/scales-utils.js
This PR addresses a number of bugs that have been present in the radial chart for a while. Chief among them are: 
- When specify a variable such as opacity that happen to all have the same value, the value default to a small value. This problem is documented in #234 
- Radial chart not updating when new props are passed. This issue was briefly referenced in #161 but didn't have a direct gh-issue about it, so I added a example that demonstrates how to build a hover, as well demonstrates the bug. 
- Untangling the mouse events in radial (#157)
> Improve Radial Chart Functionality

- src/plot/crosshair.js
if the user has custom requirements for crosshair positioning, they should be able to provide an override prop for the "left" or "right" value of `<Crosshair />`.
> allow custom crosshair orientation

- showcase/radial-chart/custom-radius-radial-chart.js
- showcase/radial-chart/simple-radial-chart.js
- src/radial-chart/index.js
- src/styles/radial-chart.scss
This PR addresses the omnipresent need to add labels to the radial plot (#39). To do so we modify the api of the radial plot in a couple of ways. We add a top level prop called showLabels to engage the labels, and two new data props, label and subLabel (See below screencap)
I think the long term solution for labels & radial plots will be to develop a labelSeries that accepts regular coordinates, and then use that in conjunction with the r-theta plot. In the mean time, this solution makes sense to me as a way to make our pie chart more ethical (label-less pie charts aint great).
> Add labels to radial plot

- showcase/treemap/simple-treemap.js
- src/treemap/index.js
The treemap currently has a prop exposed for accepting a tiling strategy, but unfortunately it was not hooked up right. This fixes that and adds some more tiling strategies.
> Add modes to treemap

- docs/xy-plot.md
- showcase/plot/complex-chart.js
- src/plot/axis/axis-ticks.js
- src/styles/examples.scss
The plot is the reference point. The old version had it inverted. 
Updated the complex-chart example to show that the changes work.
Attached image shows the example with outTicks of size 8.
> tickSizeInner should be tickSizeOuter and vice versa.  

- showcase/index.js
- showcase/radial-chart/simple-radial-chart.js
- src/plot/xy-plot.js
- src/radial-chart/index.js
- src/theme.js
- src/treemap/index.js
- src/utils/scales-utils.js
Right now the default opacity is really confusing! For some reason it imposes a range [0.1, 1], which would be cool if people weren't familiar with the normal domain of opacity for the browser, but at this point it's pretty clear. The main change in this PR is to remove this range and switch the default opacity scale to be a LITERAL so that opacity behaves closer to what users expect. This is a breaking change, and will be clustered in with the other breaking changes.
This addresses #234, #155
> Modify Default Opacity

- showcase/index.js
- showcase/treemap/circle-packed-treemap.js
- showcase/treemap/dynamic-treemap.js
- src/styles/examples.scss
- src/styles/treemap.scss
- src/treemap/index.js
- src/treemap/treemap-leaf.js
This PR adds a circle packing mode to the treemap (#153)
> Add a circle packing mode to treemap

- src/plot/hint.js
A case in Hint.js on `_mapOrientationToAlign` is wrong.
> A case is wrong in HInt.js

- src/utils/scales-utils.js
- tests/components/line-series-tests.js
- tests/utils/scales-utils-tests.js
In the case of literal scales, such as opacity, the provided value was being ignored. This fixes that and adds some tests to ensure literal scale values are honored.
> Make literal scales honor the values provided via props

- docs/xy-plot.md
When trying to import ´LinemarkSeries` instead of `LineMarkSeries`, it will give you an error.
> Fix capitalisation in docs

- src/make-vis-flexible.js
This addresses part of #147. The logic here is that the flexibility of width shouldn't be animated on first load. Also, At this point #147 is pretty stale, so I'd be willing to drop this pr if others felt it was unnecessary.
> Disable animation on flexible width when width is zero

- docs/docs-app/components/documentation-page.js
- docs/docs-app/demo.scss
- docs/markdown/axes.md
- docs/markdown/crosshair.md
- docs/markdown/grids.md
- docs/markdown/heatmap-series.md
- docs/markdown/legends.md
- docs/markdown/radial-chart.md
- docs/markdown/sankey.md
- docs/markdown/treemap.md
This PR provides a method for injecting the predefined examples from the showcase into the documentation. I think this is a stronger method than writing individual examples, because it allows us to write our testing suite against the things we are injecting. It also makes the process of adding js to markdown super smooth.
> Inject examples into markdown

- docs/markdown/series.md
- showcase/index.js
- showcase/plot/clustered-stacked-bar-chart.js
- showcase/showcase-app.js
- src/plot/series/bar-series.js
- src/styles/examples.scss
- src/utils/series-utils.js
- tests/components/bar-series-tests.js
- tests/utils/series-utils-tests.js
Fixes #292 
This is an initial proof of concept - I haven't added docs or tests yet as I wanted to validate my approach first. I also haven't added axis labels, although I'm not sure if that should be within the scope of this.
This PR adds an optional prop to `BarSeries` - `cluster` - that in the case of a vertical series a stacked bar chart into multiple stacks, keyed by that prop.
I've added an example, and attached a screenshot - would appreciate any help in getting this functionality merged in!
> Added clustered stacked bar chart

- docs/markdown/line-series.md
- showcase/plot/line-chart.js
- src/plot/series/line-series.js
- tests/components/line-series-tests.js
This enhancement (https://github.com/uber/react-vis/issues/319) allows a user to specify a custom `stroke-dasharray` attribute for the line path in a given series. This is passed down to the `LineSeries` component though the `strokeDasharray` React prop.
- Add test for enhancement
- Update documentation for enhancement
- Pass a strokeDasharray prop to a line in the `LineChart` showcase example
- Remove trailing whitespaces in `docs/markdown/line-series.md`
> Add `strokeDasharray` support for LineSeries component

- docs/markdown/bar-series.md
Change cluster from `h3` to `h4` to match siblings.
> Fix heading in BarSeries docs

- docs/docs-app/constants/pages.js
- docs/markdown/mark-series.md
- docs/markdown/series.md
- showcase/index.js
- showcase/plot/dynamic-crosshair-markseries.js
- showcase/plot/dynamic-crosshair-scatterplot.js
- showcase/showcase-app.js
- src/plot/series/abstract-series.js
- tests/components/mark-series-tests.js
This PR adds the following:
- `_getXYCoordinateInContainer ` method for `MarkSeries` which can locate the closest point in x and y space and calls `onNearestXY` prop with the closest point being returned to the callback (https://github.com/uber/react-vis/issues/327)
- Add documentation for the `onNearestXY` method (https://github.com/uber/react-vis/issues/332)
- Linting for `docs/markdown/series.md`
- Example for `onNearestXY` interaction and usage
> Implement onNearestXY for MarkSeries and add documentation

- docs/docs-app/actions/index.js
- docs/docs-app/components/documentation-page.js
- docs/docs-app/components/example-page.js
- docs/docs-app/components/header.js
- docs/docs-app/components/home.js
- docs/docs-app/components/utils.js
- docs/docs-app/constants/pages.js
- docs/markdown/examples/extensibility.md
That way we can describe why we are presenting these examples without maintaining a bunch of html!
> Allow examples to have associated markdown files

- showcase/index.js
- showcase/plot/faux-radial-scatterplot.js
- showcase/showcase-app.js
- src/index.js
- src/plot/circular-grid-lines.js
- src/plot/grid-lines.js
- src/styles/plot.scss
- tests/components/circular-grid-lines-tests.js
This PR adds a circular grid line component. This is a valuable component to have if users wish to make radial scatter plots (see below), or when making radar charts (#299)
> Circular grid lines

- docs/markdown/sunburst.md
- package.json
- showcase/index.js
- showcase/showcase-app.js
- showcase/sunbursts/animated-sunburst.js
- showcase/sunbursts/basic-sunburst.js
- src/animation.js
- src/plot/series/arc-series.js
- src/sunburst/index.js
Sunburst was previously unable to be animated due to problems with d3-interpolate's handling of deeply nested tree structures. This PR addresses this by adding a method for briefly stripping data of it's tree structure when it's about to be interpolated and then recombining with the original post animation pre-render.
> Sunburst animation

- examples/streamgraph/streamgraph-example.js
- showcase/plot/animation-example.js
- showcase/radial-chart/arc-series-example.js
- showcase/showcase-app.js
- showcase/showcase-components/showcase-button.js
- showcase/showcase-sections/axes-showcase.js
- showcase/showcase-sections/legends-showcase.js
- showcase/showcase-sections/misc-showcase.js
- showcase/showcase-sections/plots-showcase.js
- showcase/showcase-sections/radial-showcase.js
- showcase/showcase-sections/sankeys-showcase.js
- showcase/showcase-sections/sunburst-showcase.js
- showcase/showcase-sections/treemap-showcase.js
- showcase/sunbursts/animated-sunburst.js
- showcase/treemap/dynamic-treemap.js
- showcase/treemap/simple-treemap.js
- src/styles/examples.scss
- tests/components/arc-series-tests.js
The showcase app started sprawl pretty darn hard, this PR breaks it up. If we like we can break it up inside of the examples page so that people dont have to scroll as hard. Addresses some of #343
> Break apart showcase for dev legibility

- docs/markdown/line-series.md
- docs/markdown/markseries.md
- src/plot/series/mark-series-gl.js
Deck.gl supports outlines for circles, so it seems like something we should offer as well!
> Add outline mode to mark-series-gl

- showcase/index.js
- showcase/legends/horizontal-discrete-custom-palette.js
- showcase/showcase-sections/legends-showcase.js
- src/legends/discrete-color-legend.js
- src/legends/searchable-discrete-color-legend.js
- tests/components/legends-tests.js
DiscreteColorLegend has a colors default property, which should be used to pass a pass a palette (ie an array of colors). instead, it uses DISCRETE_COLOR_RANGE regardless. This is especially annoying given that DISCRETE_COLOR_RANGE is not directly accessible by users. 
in this PR, DiscreteColorLegend can take the colors property into account. 
Added an example.
> Fix discrete color legend

- src/plot/axis/axis-line.js
- src/plot/series/label-series.js
- src/plot/series/line-mark-series.js
- src/radial-chart/index.js
- src/sunburst/index.js
This PR fixed some invalid use of PropTypes across the library:
- `AxisLine` and `LineMarkSeries` still use the deprecated `React.PropTypes`
- `LabelSeries`, `RadialChart` and `Sunburst` declared them via `Component.PropTypes` instead of `Component.propTypes`.
> Fix PropTypes.

- docs/markdown/borders.md
- showcase/misc/gradient-example.js
- showcase/showcase-app.js
- showcase/showcase-sections/misc-showcase.js
- src/index.js
- src/plot/borders.js
- tests/components/borders-tests.js
- tests/index.js
- yarn.lock
When domain is set on the XYPlot the series that it contains can sometimes spill over into margin. One potential solution would be to not allow overflow, however this can be limiting because of the relatively flat structure of the XYPlot. The most versatile solution (imo) is to create a Borders component that is directly correlated to the margins of the plot. That way the user can embed it into the structure of their chart however they wish. 
This addresses issue #407
> Add borders component

- docs/markdown/sankey.md
- src/sankey/index.js
- tests/components/sankey-tests.js
Display by default the `name` property of the nodes as labels.
Also provides a `hideLabels` property, turned off by default
> feat(sankey): add labels support

- .gitignore
- bundle.js
- markdown/decorative-axis.md
- markdown/examples/zoomable-chart.md
- markdown/hint.md
- markdown/sankey.md
Github was ignoring new updates to the docs page because it's jekyll interpreter was invalidating a bunch of jsx syntax we had (eg something like "style={{fontSize: 14}}", would be invalid because it didn't terminate as a jekyll variable correctly).
> Upgrade the docs & Dont Jekyll

- src/radial-chart/index.js
Removes the JS errors caused on all examples
> RadialChart data PropType=Array

- docs/markdown/radial-chart.md
- showcase/radial-chart/donut-chart.js
- src/plot/series/arc-series.js
- tests/components/radial-tests.js
Addresses #444 
Within a `RadialChart`, a custom className for an arc can be passed in through `data`.
```jsx
<RadialChart
data={[
{angle: 2, className: 'custom-class'},
{angle: 1}
]}
/>
```
> arc-series can receive classNames from RadialChart data

- src/plot/series/abstract-series.js
- src/plot/series/label-series.js
- src/radial-chart/index.js
The LabelSeries used by RadialChart has been throwing console errors because RadialChart reports it's positions in polar coordinates (while LabelSeries was expecting cartesian!). This addresses #451
> Modify prop types to remove error

- docs/docs-app/constants/pages.js
- docs/markdown/markseries.md
- docs/markdown/radar-chart.md
- showcase/index.js
- showcase/radar-chart/animated-radar-chart.js
- showcase/radar-chart/basic-radar-chart.js
- showcase/showcase-app.js
- showcase/showcase-sections/radar-showcase.js
- src/plot/axis/decorative-axis-ticks.js
- src/plot/axis/decorative-axis.js
- src/plot/series/abstract-series.js
- src/radar-chart/index.js
- src/utils/axis-utils.js
- tests/components/decorative-axis-tests.js
- tests/components/radar-chart-tests.js
- tests/index.js
- tests/utils/axis-utils-tests.js
This PR adds a new basic chart type: the long awaited radar chart (#299). Couple of small things still to do, but i think it should be ready for review.
Open to any suggestions on how to improve the API. Right now we simply ask users to provide rows of polygons for the data prop, and row of domains, like so 
```javascript
const RADAR_PROPS = {
data: [{
explosions: 7,
wow: 10,
dog: 8,
sickMoves: 9,
nice: 7
}],
domains: [
{name: 'nice', domain: [0, 100]},
{name: 'explosions', domain: [6.9, 7.1]},
{name: 'wow', domain: [0, 11]},
{name: 'dog', domain: [0, 16]},
{name: 'sickMoves', domain: [0, 20]}
],
height: 300,
width: 400
};
```
Where the order of the domains provide the order of the axes. Here are some questions:
- It doesn't accept children but it could! I am unsure if that's a good idea …
> Radar chart

- docs/markdown/radar-chart.md
- showcase/radar-chart/animated-radar-chart.js
- src/radar-chart/index.js
- tests/components/radar-chart-tests.js
This PR enables the radar chart to accept children, this can be useful for adding axes, as below.
Addresses #470
> Allow radar chart to accept children

- docs/markdown/radar-chart.md
- showcase/radar-chart/basic-radar-chart.js
- src/radar-chart/index.js
This PR adds a new prop to radar chart, startingAngle. Like the name suggests it allows the user to specify what the initial angle for the first axis is. Addresses #469
> Intro a startingAngle parameter to the radarChart

- docs/markdown/radar-chart.md
- showcase/radar-chart/basic-radar-chart.js
- src/radar-chart/index.js
- tests/components/radar-chart-tests.js
This PR ensures that tickFormat can be specified at any level in the Radar chart. Addresses #468
> Enforce a hierarchy of tickFormats

- docs/markdown/sunburst.md
- showcase/sunbursts/basic-sunburst.js
- src/sunburst/index.js
- tests/components/sunburst-tests.js
It can be useful to allow users to inject children into the Sunburst, so as to annotate them.
> Allow sunbursts to have children

- docs/markdown/radar-chart.md
- showcase/radar-chart/basic-radar-chart.js
- src/radar-chart/index.js
- tests/components/radar-chart-tests.js
Previously we were pre-sorting the domains for the decorative-axes. This had the effect that half of the axes would be weirdly labeled. The radar chart should now respect the prescribed domain.
(Note that the warranty axis is intentionally flipped, to show that order matter). This addressed #477
> Dont sort radar domains

- showcase/radar-chart/animated-radar-chart.js
- src/radar-chart/index.js
> Radar center label text by default

- docs/markdown/hint.md
- showcase/index.js
- showcase/showcase-sections/sunburst-showcase.js
- showcase/sunbursts/sunburst-with-tooltips.js
- src/plot/series/arc-series.js
- tests/components/radial-tests.js
- tests/components/sunburst-tests.js
An unfortunate fact about life is that d3's polar coordinate system is not the same as the usual polar coordinate system. Specifically, d3 does clockwise starting at 12, while convention goes counter clockwise starting at 3. This difference caused frequent mis-reporting of mouseover values for charts that made use of the arc-series. This PR adds assurance that the number reported onMouseOver/onMouseOut/onClick is the correct one.
Before
After
This bug was not that noticeable on radial charts (see above), though it was there. It was significantly more pronounced on sunbursts. The new example I added to show how to use tooltips on sunbursts shows the a good way to deal with this:
This addresses #483
> Arc series reporting incorrect mouse over values

- showcase/plot/histogram.js
- showcase/plot/stacked-histogram.js
- src/plot/series/horizontal-rect-series-canvas.js
- src/plot/series/horizontal-rect-series.js
- src/plot/series/vertical-rect-series-canvas.js
- src/plot/series/vertical-rect-series.js
For rect series one of the scales can get adjusted, just like for bar series, even though the user has control on both sides of the rectangle.
For instance (as highlighted in issue 492) for vertical bar series, x scale gets adjusted, even though user can control the position of the left and right edge of each mark. 
(likewise for horizontal rect series, y scale could get adjusted.)
> fixes issue #492

- showcase/plot/contour-series-example.js
- showcase/plot/line-chart-canvas.js
- showcase/plot/scatterplot-canvas.js
- src/animation.js
- src/plot/series/bar-series-canvas.js
- src/plot/series/canvas-wrapper.js
- src/plot/series/line-series-canvas.js
- src/plot/series/mark-series-canvas.js
- src/plot/series/rect-series-canvas.js
- src/plot/xy-plot.js
This PR adds an animated canvas drawing system for the canvas components. Similarly to the regular animation system it runs on d3-interpolate, however we have to do the animation work ourself, because we are directly manipulating the canvas. This addresses #417 
It runs a little clumsily when there are multiple animations running at once. Would be delighted to hear what someone who knows this stuff better has to say. That said, when it runs well, it runs significantly more smoothly than the same svg animations for medium volume data
(This PR Also update canvas so that there is a margin on the canvas itself.)
> Add a naive canvas animation system

- docs/docs-app/constants/pages.js
- docs/markdown/contour-series.md
- docs/markdown/custom-svg-series.md
- showcase/index.js
- showcase/misc/label-series-example.js
- showcase/plot/custom-svg-all-the-marks.js
- showcase/plot/custom-svg-example.js
- showcase/showcase-sections/plots-showcase.js
- src/index.js
- src/plot/series/custom-svg-series.js
- src/plot/series/label-series.js
- tests/components/custom-svg-series-tests.js
- tests/index.js
This PR adds a custom svg series. This series adds a ```<g>``` element based on an xy coordinate, and the fills it with a custom component. 
Usage is like this:
```jsx
<CustomSVGSeries
className="custom-marking"
customComponent="square"
data={[
{x: 1, y: 10, customComponent: 'circle', size: 10},
{x: 1.7, y: 12, size: 20, style: {stroke: 'red', fill: 'orange'}},
{x: 2, y: 5},
{x: 3, y: 15},
{x: 2.5, y: 7, customComponent: (customComponent, positionInPixels) => {
return (
<g>
<circle cx="0" cy="0" r={10} fill="green"/>
<text x={0} y={0}>
<tspan x="0" y="0">{`x: ${positionInPixels.x}`}</tspan>
<tspan x="0" y="1em">{`y: ${positionInPixels.y}`}</tspan>
</text>
</g>
);
}}
]}/>
```
Where the contents of the custom component can be declared on the series level or on the row level. They can be …
> Custom SVG series

- docs/markdown/sunburst.md
- showcase/sunbursts/animated-sunburst.js
- showcase/sunbursts/sunburst-with-tooltips.js
- src/sunburst/index.js
- tests/components/sunburst-tests.js
Adds potential for tooltips on sunburst, as requested in #529
> Add labels to sunburst nodes

- docs/markdown/examples/responsive-vis.md
The links to the two responsive examples were broken. This should fix it.
> Fix links to response examples

- docs/markdown/legends.md
Looks like in https://github.com/uber/react-vis/pull/135/files#diff-54315c7bb8c76d7c2bdbdd4debd1bb53R28 the option for horizontal legends was added. I've confirmed it does indeed work:
> add missing orientation prop to DiscreteColorLegend documentation

- docs/markdown/treemap.md
- showcase/treemap/dynamic-treemap.js
- showcase/treemap/simple-treemap.js
- src/styles/examples.scss
- src/treemap/index.js
- src/treemap/treemap-dom.js
- src/treemap/treemap-leaf.js
- src/treemap/treemap-svg.js
- tests/components/treemap-tests.js
An occasionally frustrating thing about the treemap is that it is the only chart type in react-vis that doesn't support SVG. This PR adds a SVG mode to tree map (#431) which could also be trivially extended to be canvas. 
Additionally this PR enables some inline style options which hadn't made their way to Treemap yet (#541)
> Enable SVG mode on treemap

- showcase/sunbursts/animated-sunburst.js
- showcase/sunbursts/basic-sunburst.js
- src/plot/series/arc-series.js
- src/sunburst/index.js
- tests/components/arc-series-tests.js
- tests/components/radial-tests.js
- tests/components/sunburst-tests.js
This PR Addresses #510 and provides a technique for addressing #381. 
It is often the case that the animation component clobbers listeners. This can be super confusing! One solution is to slightly modify the way that we call animation to lay a shadow "listener layer" on top of the render SVG. This allows us to separate the concerns between calling events and making good animation.
> Make arc listeners respect mouse events during animation

- src/make-vis-flexible.js
- tests/components/make-vis-flexible.js
- tests/index.js
When using the HOC `makeWidthFlexible` the resulting component will look like this:
```html
<Flexibleundefined ...>...</Flexibleundefined>
```
It can be fixed by explicitly setting a displayName:
```js
MyComponent.displayName = 'MyComponent';
makeWidthFlexible(MyComponent);
```
I think the `makeWidthFlexible` HOC should fallback to use the component name, if no display name is given. This will always be more useful than `undefined`
> Use component name as fallback for display name

- package.json
- yarn.lock
As reported in #560, we explicitly use d3-format in a few places but do not have it listed as an explicit dependency.
> Add d3-format to package.json

- docs/markdown/arc-series.md
- docs/markdown/bar-series.md
- docs/markdown/heatmap-series.md
- docs/markdown/interaction.md
- docs/markdown/label-series.md
- docs/markdown/line-mark-series.md
- docs/markdown/line-series.md
- docs/markdown/mark-series.md
- docs/markdown/polygon-series.md
- docs/markdown/rect-series.md
- docs/markdown/sunburst.md
- docs/markdown/whisker-series.md
- src/plot/series/abstract-series.js
- src/plot/series/arc-series.js
- src/plot/series/area-series.js
- src/plot/series/bar-series.js
- src/plot/series/heatmap-series.js
- src/plot/series/label-series.js
- src/plot/series/line-series.js
- src/plot/series/mark-series.js
- src/plot/series/polygon-series.js
- src/plot/series/rect-series.js
- src/plot/series/whisker-series.js
- src/sunburst/index.js
- tests/test-utils.js
this PR allows users to handle right clicks to either marks or series. Each time a vis can handle an onValueClick, there is now an onValueRightClick; likewise, every series that supported onSeriesClick now supports onSeriesRightClick. 
documentation updated. 
no new tests are provided, since onValueClick wasn't tested per se, but it doesn't break existing tests.
> handle right clicks to series and marks

- src/radar-chart/index.js
It is already defined in the default props but the rendering
unconditionally uses the default color range.
> RadarChart: support colorRange prop

- showcase/misc/label-series-example.js
- src/plot/series/label-series.js
- tests/components/label-series-tests.js
This PR addresses #579, in that it prevents the label series from interpolating it's labels. They simply jump from one to the text. This PR is a little bit hacky and is not the only time we've run into weirdness around d3-interpolate, so I've opened an issue with d3-interpolate (which generates our interpolations), https://github.com/d3/d3-interpolate/issues/42
> Dont let labels interpolate

- docs/markdown/custom-svg-series.md
- showcase/plot/custom-svg-all-the-marks.js
- showcase/plot/custom-svg-example.js
- src/plot/series/custom-svg-series.js
The style prop on custom-svg-series was not using the style prop effectively, so I moved it around so that it is applied to each element, rather than the containing g. This PR addresses #594
> Add global styles for custom svg series

- docs/xy-plot.md
- src/plot/xy-plot.js
- src/sunburst/index.js
- src/treemap/treemap-svg.js
When building the sunburst I added a function called cleanseData which makes a copy of every element under consideration in the xy-plot. This is useful for sunburst and treemap as it allows us to remove cyclic structures in the json, however as noted in #593, this can cause some serious performance bottle neck. This PR delegates that functionality under a flag to keep things moving quickly unless necessary.
> Only try to clean data when asked

- README.md
- src/plot/series/canvas-wrapper.js
- src/plot/xy-plot.js
Using `devicePixelRatio` allows us to improve the visual quality of canvas renderings by accounting for the ratio between physical and virtual pixels. Most notably, canvas charts will look much better on Apple's Retina Displays.
**Before**
**After**
> Use window.devicePixelRatio to sharpen canvas images

- docs/treemap.md
- src/treemap/index.js
- tests/components/treemap-tests.js
The node size property does not exist  when sorting is performed in the current code.  From the [d3-hierarchy docs](https://github.com/d3/d3-hierarchy#node_sum) sum should be called first to set the value property.  Then sort can be called to sort the node on value.
I also used the reccomended sort functions from that doc. We may want to move sortFunction to a prop allowing a user to override these.
Adjusting the sorts, created treemaps that are more organized, flowing from largest to smallest
Now
vs
Before
> Fix treemap sorting 

- showcase/index.js
- showcase/plot/custom-svg-root-level.js
- showcase/showcase-sections/plots-showcase.js
- src/plot/series/custom-svg-series.js
- tests/components/custom-svg-series-tests.js
This PR enables custom-svg-series to accept a root level function to describe the custom component for the entire series. Like all good PRs it comes with a new example
> Enable customComponent to be defined at root level

- docs/axes.md
Update `tickFormat` example to show exposed index from https://github.com/uber/react-vis/pull/615 and https://github.com/uber/react-vis/issues/616
> Update `tickFormat` example in `axis.md docs with exposed index

- src/main.scss
- src/plot/xy-plot.js
- src/utils/react-utils.js
One of the most common issues users run into is forgetting to import the stylesheet (#602). This PR adds a small script that looks through the styles sheets that are being used in the browser and evaluates whether or not a "magic css rule" is found. (This magic css rule doesn't do anything except add a tag to the minified css name space) If we are unable to find this rule, it implies the style sheet has not been imported, so we give a warning.
> Check if stylesheet has been imported

- package.json
Hi!
Quick one liner so there aren't errors when upgrading to React 16 - from a quick poke around everything seems to be working
I haven't updated any of test harness yet, there's some work to do with Enzyme to get things going there.
> Updating peer dependencies to allow React 16

- src/treemap/index.js
The margin prop wasn't being used by the treemap.  Instead the const DEFAULT_MARGINS was being used.
This fixes that behavior allowing the user to set the margin prop
> Treemap margin property not used

- docs/sankey.md
- showcase/index.js
- showcase/sankey/link-event.js
- showcase/showcase-sections/sankeys-showcase.js
- src/sankey/index.js
- src/sankey/sankey-link.js
- tests/components/sankey-tests.js
This commit adds onClick, onMouseOver, and onMouseOut event handlers to
the link SVG paths on Sankey charts. I've also added a quick example to
the showcase.
Will be useful for #631
> Add event handlers to Sankey links

- package.json
- yarn.lock
Moves react-test-renderer from `dependencies` to `devDependencies` since I doubt it's actually needed to use the library
> Move react-test-renderer to devDependencies

- src/treemap/index.js
The height and width need to be swapped when using a partition pivot.  Otherwise the treemap will flow out of the container.
Old behavior
Fixed behavior
> Swap height and width in partition pivot treemaps

- src/treemap/index.js
- tests/components/treemap-tests.js
There was no sort for the partition treemap before, added that in to match the other modes.
> Added sort to partition treemap

- docs/treemap.md
- src/treemap/index.js
- src/treemap/treemap-dom.js
- src/treemap/treemap-svg.js
- tests/components/treemap-tests.js
Added a  property to treemap hideRootNode with a default of false as discussed in #639 with @mcnuttandrew 
This did cause some changes in the number of nodes for existing treemaps.  I updated the tests and added a new test for this property.
This did result in visual changes for some treemaps.  
Partitions now show the root node(the desired result)
New
vs Old
For squarify there is a slight change in the space between the node padding(where the root node becomes visible)
New
vs old
> Added treemap hideRootNode property

- showcase/axes/custom-axis.js
- src/plot/axis/axis-title.js
- tests/components/axes-tests.js
issue: #651 
I am now applying the style to the text inside of the axis title.
I changed the showcase so that the custom axis chart shows that the user can change the font. 
I added a test to test if the style is being applied to the correct title.
> Fix axis title style bug

- src/utils/react-utils.js
This PR fixes the `SecurityError` that is thrown in development mode for Firefox. 
See: https://github.com/uber/react-vis/issues/650 for more context.
I tested it in Firefox 58 and Chrome 60.
> Fix firefox SecurityError in development

- src/plot/xy-plot.js
- src/utils/scales-utils.js
- tests/utils/scales-utils-tests.js
This PR addresses #663 by refactoring getOptioanlScaleProps into a little less cutting edge state, and pulling it into a utils file. In it's current state this function seems kinda unnesscary, like it seems like a lot of overkill just to test for the presence of a padding prop, but that's not the point of this PR. The point of this PR is to unbreak this function on IE11.
> Refactor getOptionalScaleProps, add tests, IE11 support

- src/utils/react-utils.js
In some cases when `npm start` is executed for local development, the 
`return styleSheet.rules || styleSheet.cssRules;` line will cause Firefox to crash with the issue presented below.
This happens when `checkIfStyleSheetIsImported();` is called in `XYPlot` class. 
What's interesting is that if any kind of a blocking call is added above the offending line, such as `alert()`, the page loads just fine, which leads me to believe that the `styleSheets` might not be parsed fast enough and it's property `cssRules` is accessed before that happens.
Possibly relevant bugs:
[https://bugzilla.mozilla.org/show_bug.cgi?id=625013](url) 
[https://bugzilla.mozilla.org/show_bug.cgi?id=761236](url)
However, as these were reported 6 years ago and no progress has been made since, I don't think that this is …
> Prevent Firefox from crashing if styleSheet doesn't get parsed fast enough. (Local development)

- src/utils/series-utils.js
- tests/utils/series-utils-tests.js
I just created a PR so we can further discuss the code. I am not sure if I misunderstand something, but the tests fail while the changes render the example stacked charts nicely. It also works well with a bunch of data on my project (gives the result I have shown in the Issue). 
I am not sure if there is a difference between VerticalBarSeries and HorizontalBarSeries regarding the stackBy value, but from my understanding setting stackBy='y' on HorizontalBarSeries doesn't make much sense, thus the following test code will not work correctly:
```
let children = [
(<HorizontalBarSeries
data={yData[0]}
/>),
(<HorizontalBarSeries
data={yData[1]}/>),
(<div> i think i will by that lamp </div>)
];
let results = getStackedData(children, 'y');
let expectedResults = [[
{x: 10, y: 2},
{x: 5, y: 4}, …
```
> Modified getStackData function to also work with partial data

- src/utils/react-utils.js
In browser render this was erroring: 
```
VM469 client-vendor.js:68616 Uncaught ReferenceError: process is not defined
at checkIfStyleSheetIsImported (VM469 client-vendor.js:68616)
at XYPlot.componentDidMount (VM469 client-vendor.js:65809)
at commitLifeCycles (VM469 client-vendor.js:46266)
```
> Avoid process reference error

- docs/crosshair.md
- showcase/axes/dynamic-crosshair.js
- src/plot/crosshair.js
- tests/components/crosshair-tests.js
- tests/index.js
For apps that use inline styles, the cross does not get positioned correctly because the crosshair is positioned absolutely. Expose `className` on this component so that applications using inline styles can hook into this component
> Expose `className` prop on Crosshair component and update docs

- docs/scales-and-data.md
Describes how one would add d3 based localization for time series charts.
> Added a 'Localization' section in 'Scales and data' documentation

- docs/interaction.md
- docs/xy-plot.md
- showcase/examples/zoomable-chart/highlight.js
- src/plot/series/abstract-series.js
- src/plot/voronoi.js
- src/plot/xy-plot.js
- tests/components/crosshair-tests.js
- tests/components/dragable-chart-tests.js
This PR resolves https://github.com/uber/react-vis/issues/751 and adds support for touch devices for the following features:
- Crosshair functionality
- Draggable charts
- Zoomable charts
It does so in a manor that is unobtrusive and allows for some flexibility. The main gotcha with touch events is that `touchmove` is very different from the way `mouseover` and `mouseout` work, in the sense of you have to listen for `touchmove` on a larger container of elements, and use DOM APIs at our disposal to determine which child nodes the user is currently touching. We are unable to bind listeners for `touchmove` on the child components, as the target originates from the node `touchstart` was fired on.
I have added some documentation around new props on the XY Plot and I have also added tests. …
> Implement touch behaviors

- showcase/showcase-components/showcase-utils.js
- src/styles/examples.scss
- website/yarn.lock
- yarn.lock
- Removes the `source` link: I always found it confusing that we had this link when almost always you want to inspect the example code, not the source code of the underlying series.
- Styling changes to clean up the remaining two links (view code, and documentation)
**Before**
**After**
> Clean up links on the Showcase Page

- docs/xy-plot.md
- src/plot/series/abstract-series.js
- src/plot/series/contour-series.js
- tests/components/xy-plot-tests.js
- tests/utils/scales-utils-tests.js
Fixes #724. This change will prevent prop-validation for throwing a warning when users use `data` accessors (for using arrays, for example).
> Better PropType validation for data in AbstractSeries; Tests for using Accessors

- README.md
Instead of ./node_modules which only works if the file is at root, ~ always resolves to the node_modules folder.
> Fix scss import path

- docs/label-series.md
- Fixed a typo in [data].style
```javascript
const myData = [
{x: 0, y: 0, label: 'woah!', style={fontSize: 10}}, // wrong => style: {fontSize: 10}
{x: 1, y: 0, label: 'dope city', yOffset: 5},
{x: 0, y: 1, label: 'cool Dog friend', xOffset: 5, rotation: 34}
]
```
> fix(docs): Fix LabelSeries docs - style

- docs/axes.md
- showcase/axes/custom-axis-tick-format.js
- showcase/index.js
- showcase/showcase-sections/axes-showcase.js
- src/plot/axis/axis-ticks.js
In the `AxisTicks` component, the custom `tickFormat` method currently only gets passed a tick value and index. There are cases where one would want to change the formatting of the tick using the d3-scale tickFormat function with custom parameters. Which allows to format values using the various d3-format options on the scale (according to the actual value range) and make further custom adaptations to the tick label.  
e.g. use SI-prefix plus additional unit -> "1.2kWh"
**Existing behavior (from [docs](https://github.com/uber/react-vis/blob/master/docs/axes.md#tickformat-optional)):**
```javascript
function myFormatter(t, i) {
return (<tspan>
<tspan x="0" dy="1em">MY VALUE</tspan>
<tspan x="0" dy="1em">{t}</tspan>
</tspan>);
}
```
**Desired behavior:**
```javascript
function …
```
> Expose scale and tickTotal to custom tickFormat function at axis

- docs/series.md
This PR tries to fix #806 (Dead link to bar series doc)
Currently I only fix `series.md` (which maps to `documentation/api-reference/series`), but this issue  actually happens in all markdown generated pages. It causes developers hard to read documentations online.
The root cause is that we're using filename as link destination rather than url. For example, we have following content in `series.md`:
```markdown
See the [XYPlot](xy-plot.md)'s `animation` section for more information.
```
The above `xy-plot.md` is a filename rather than a link. 
This patch works in my local build, and if this is acceptable I can help to further review the rest docs.
> Fix the broken link in series.md

- showcase/examples/candlestick/candlestick.js
- showcase/examples/responsive-vis/responsive-vis-example.js
- src/make-vis-flexible.js
- src/plot/axis/decorative-axis.js
- src/plot/series/arc-series.js
- src/plot/series/bar-series.js
- src/plot/series/canvas-wrapper.js
- src/plot/series/contour-series.js
- src/plot/series/custom-svg-series.js
- src/plot/series/heatmap-series.js
- src/plot/series/label-series.js
- src/plot/series/mark-series.js
- src/plot/series/rect-series.js
- src/plot/series/whisker-series.js
I just ran into https://github.com/uber/react-vis/issues/736 and this will probably fix it
> Chore(ReactVis): Remove String Refs

- src/radar-chart/index.js
- src/utils/axis-utils.js
I ran into the same issue (#796).  The RadarChart axes does not show or is displayed incorrectly (ex. wrong number of ticks) depending on what the startingAngle is.  Rotating your graph a certain degree can cause these problems, because JavaScript's trigonometric functions (ex. Math.sin & Math.cos) can return numbers with floating point errors (see table below). These floating point numbers can cause calculation errors.
Trig Function | Angle | JavaScript Value | True Value
--- | --- | --- | ---
*sin* | PI | 1.2246467991473532e-16 | 0
*cos* | PI/3 | 0.5000000000000001 | 0.5
Shown below is what I used for my RadarChart.
```
class App extends Component {
render() {
const RADAR_PROPS = {
data: [{
C: 30,
VisualBasics: 60,
Excel: 40,
Access: 40
}],
domains: [
{name: 'C', domain: [0, 100]}, …
```
> Fixes RadarChart axes (#796)

- showcase/examples/candlestick/candlestick.js
- src/plot/axis/decorative-axis.js
- src/plot/series/arc-series.js
- src/plot/series/bar-series.js
- src/plot/series/contour-series.js
- src/plot/series/custom-svg-series.js
- src/plot/series/heatmap-series.js
- src/plot/series/label-series.js
- src/plot/series/mark-series.js
- src/plot/series/polygon-series.js
- src/plot/series/rect-series.js
- src/plot/series/whisker-series.js
- src/plot/xy-plot.js
- src/utils/series-utils.js
- tests/utils/series-utils-tests.js
I was hoping that the latest version bump would solve #736 - and it does not.
This time I ran `yarn link` and made sure to get rid of remaining string `ref`s.
> Chore(ReactVis): Remove Refs

- docs/series.md
- docs/xy-plot.md
Currently these links point to files in nonexistent directories. This pull request resolves those references so that they no longer 404.
> Fix documentation links in docs/series.md and docs/xy-plot.md

- docs/interaction.md
- docs/xy-plot.md
- src/plot/xy-plot.js
- tests/components/xy-plot-tests.js
This PR integrate and fix the following:
1. The jsdocs of XYPlot mouse handlers are updated and describe events passed to the handler as SyntheticEvent
2.  Callback of some XYPlot mouseEvents handlers are called directly with the events, some other with an object like `{event: event}`. I've aligned all the callbacks
3. Added the `onParentMouseLeave` and `onParentMouseEnter` callbacks for series components. Although this is not directly used by components in `react-vis` I think there are cases where a developer wants to extend an `AbstractSeries` and needs the `onParentMouseUp` or onParentMouseLeave events. We are for example on creating our own Crosshair but extending an `AbstractSeries` so we have the access to all the plot data as props in side the component. Having `onParentMouseLeave` …
> Align onParentEventType callbacks across XYPlot

- .eslintrc
- package.json
- showcase/axes/axis-on-0.js
- src/treemap/treemap-dom.js
- tests/components/radial-tests.js
- yarn.lock
I wish there was a lint rule for this ugh
> Accidentally turned off all of the tests but one

- src/plot/xy-plot.js
- tests/setup.js
00ffe61 tries to set the `ref` attribute on stateless components - which causes loads of console errors.  This fix only sets the `ref` attribute on components which were previously receiving it.
#861
> Fix(ReactVis): Stop Setting Refs On Stateless Components

- src/plot/xy-plot.js
This should solve #861.  
I am unsure why #867  did not succeed.  I thought I saw that solve the issue while `yarn link`-ed to an example.
> Check if stateless before adding ref

- docs/xy-plot.md
- showcase/axes/empty-chart.js
- showcase/index.js
- showcase/showcase-links.js
- showcase/showcase-sections/plots-showcase.js
- tests/components/xy-plot-tests.js
Addresses some points raised in #845. I built this feature a long time ago, but never documented it because it was mostly for internal use. In between now and then I had forgotten I made it, and had frequently wished for it to exist, this documentation will hopefully be a reminder this function is around.
> No documentation on how to make empty charts

- .prettierrc
- package-lock.json
- publish-docs.sh
- website/package-lock.json
- website/package.json
- website/src/mdRoutes.js
- website/yarn.lock
I just bumped the docs and these are some changes that were necessary along the way.  Also happy to break these changes up into separate PRs.
- Adds a line for robustness to `publish-docs.sh`
- Updates a broken path in  `website/src/mdRoutes.js`
- Adds `.pretterrc` because large changes were happening in `website/src/mdRoutes.js` (adding `.prettierrc` only mitigated that problem slightly)
- Updates out of date .lock files
- Moves the ocular build after the storybook build because it seemed to be wiping out storybook
> Chore(Docs): Update Docs Changes

- docs/line-series.md
- showcase/plot/line-chart.js
- showcase/plot/linemark-chart.js
- src/plot/series/line-series-canvas.js
- tests/components/line-series-tests.js
> Add curves to LineSeriesCanvas

- src/sankey/index.js
> center sankey chart labels

- src/sankey/index.js
> sankey chart: fix labels' horizontal position

- docs/voronoi.md
- showcase/axes/dynamic-crosshair-scatterplot.js
- showcase/misc/voronoi-line-chart.js
- src/plot/voronoi.js
- tests/components/voronoi-tests.js
At long last this PR addresses #355. It enables the voronoi component to automatically pick up the extent and scales for the current XYPlot. It also makes the API mostly conform to the rest of the react-vis style (#821). Finally, and most interestingly, I believe that this PR enables throwing voronois over non-linear scales. 
It is backwards compatible with the current usage, so nothing should break!
> Make voronoi component automatically infer scales and extent

- docs/arc-series.md
- docs/radial-chart.md
- docs/sunburst.md
- showcase/radial-chart/donut-chart.js
- showcase/sunbursts/sunburst-with-tooltips.js
- src/plot/series/arc-series.js
- src/radial-chart/index.js
- src/sunburst/index.js
- tests/components/radial-tests.js
Currently there are no means to add padding between arcs on a RadialChart. This PR seeks to enable such capability.
> Include option for padAngle on RadialChart

- showcase/plot/complex-chart.js
It has always bother me how the edge of the complex chart would go over the axis. 
Before
After
> Adjust edge of complex chart

- docs/series.md
- docs/xy-plot.md
A few links inside documentation were pointing to the wrong place. 
I also added some more links for consistency.
> Fixing some documentation links

- src/utils/scales-utils.js
- tests/utils/scales-utils-tests.js
> Fix `getY0` prop on AreaSeries

- docs/interaction.md
The markdown text was incorrectly formatted, and caused text to appear inside a code block.
> Fix markdown formatting

- docs/examples/iris-dashboard.md
- showcase/examples/iris-dashboard/iris-dashboard.js
- showcase/examples/iris-dashboard/iris-dashboard.scss
- showcase/showcase-app.js
- showcase/showcase-index.js
- website/src/mdRoutes.js
Did you know we are required by law as an internet charting library to have a small multiples display of the iris data set? 
This PR adds a small multiples matrix for the iris dataset i added a little while ago. It provides a nice replacement to the zoom examples.
> Add iris small multiples example

- docs/bar-series.md
- showcase/index.js
- showcase/plot/difference-chart.js
- showcase/showcase-sections/plots-showcase.js
- tests/components/bar-series-tests.js
This PR answers a question @alee8 asked me via email about how to make this type of chart.
> Add example of difference bar chart

- docs/legends.md
- showcase/legends/searchable-discrete-color.js
- src/legends/discrete-color-legend-item.js
- src/legends/discrete-color-legend.js
- src/styles/legends.scss
- tests/components/legends-tests.js
Added the ability to set stroke properties (strokeDasharray, strokeStyle, strokeWidth) of Discrete Color Legend items to match Line Series components. At first I considered mimicking the `colors` attribute and letting users add a `strokeWidths` array, but it seemed to over-complicate the api, so I settled with grabbing those properties from an `item`'s object.
The legend items now render an svg path instead of a 2x14px div, which was necessary to match the dash-array property, but it also might help keep the legend consistent with the chart.
I edited one of the legend examples to show the implementation - happy to remove it if it's too heavy-handed.
Happy to hear any feedback, thanks!
> add stroke properties to discrete color legend (#860)

- showcase/plot/clustered-stacked-bar-chart.js
- src/legends/discrete-color-legend.js
- tests/components/legends-tests.js
Fixes #893 
This should retain any `style`s passed to DiscreteColorLegend
I updated the example so the styles actually change the legend position, and didn't forget a test this time :raised_hands:
> propagate props for discrete color legend

- showcase/legends/horizontal-discrete-color.js
- showcase/legends/searchable-discrete-color.js
- showcase/showcase-sections/legends-showcase.js
- tests/components/legends-tests.js
I thought that adding another legend might crowd the examples, so I changed the horizontal legend example to use the new stroke style properties. Let me know if you think this is overloaded and I can break it out!
> Update HorizontalDiscreteColor example to show off stroke style properties

- docs/custom-svg-series.md
- docs/radar-chart.md
- showcase/index.js
- showcase/plot/custom-svg-all-the-marks.js
- showcase/radar-chart/radar-chart-series-tooltips.js
- showcase/radar-chart/radar-chart-with-tooltips.js
- showcase/showcase-links.js
- showcase/showcase-sections/plots-showcase.js
- showcase/showcase-sections/radar-showcase.js
- src/plot/series/custom-svg-series.js
- src/plot/series/polygon-series.js
- src/radar-chart/index.js
- tests/components/custom-svg-series-tests.js
- tests/components/radar-chart-tests.js
This is a pull request for the issue I logged recently: https://github.com/uber/react-vis/issues/959
This has a few changes:
1. `RadarChart` - add the option to display axes on top of the polygons. I have charts with high opacity that cover the axes labels. I added a prop to give the option to render the axes on top (false by default). (The 1, 2, 3, 4 labels in the screenshot below illustrate this.)
2. `CustomSvgSeries` - ]add `onMouseOver`/`onMouseOut` events
- Showcase (and tests) updated to show an example:
3. `RadarChart` - Tooltips on the Polygon corners.
- Added `onValueMouseOver` and `onValueMouseOut`
- Circle rendered transparently with `MarkSeries` - has a `size` of 14 so that the mouse just needs to be close to the point to show the tooltip.
- This screenshot is an example that …
> Radar chart tooltips

- docs/bar-series.md
- src/plot/series/bar-series.js
Make the bar width percentage, which was hardcoded to 85% by default, a prop that is passed to the BarSeries class.
> Make bar width (percentage) a prop for Bar Series

- src/plot/series/custom-svg-series.js
Fixes #1010 
While using CustomSVGSeries with either x or y ordinal values, the AbstractSeries threw a warning - 
Fix in this PR allows the proptypes of the x, y values to be `string`|`number`
> Typecheck: fixed proptypes of the data coordinates in CustomSVGSeries

- package-lock.json
- package.json
- yarn.lock
It is really easy to accidentally break the react-vis build by forgetting to remove unpm delivered packages. This has happened many many times. This PR adds pre push hook stop unpm packages from entering a PR.
This can also be used to create other hooks (like a prepublish hook that we've sought for a long time). 
I don't know too much about husky, but it looks legit and the folks who use it are credible. Let me know if you have any thoughts.
> Install a pre-push hook for removing unpm

- docs/axes.md
- showcase/axes/custom-axis-tick-element.js
- showcase/index.js
- showcase/showcase-sections/axes-showcase.js
- src/plot/axis/axis-ticks.js
- tests/components/axis-tick-format-tests.js
- tests/index.js
right now the value rendered from `tickFormat` will always be wrapped in a `<text>` node which is quite limiting if you want to do more flexible stuff. this change checks if the value that's returned from `tickFormat` is a React element and renders it instead of the `<text>` in case it is one. the custom element also gets passed the width of the tick container and the total amount of ticks as props in case it wants to do some responsive stuff.
~as such, this would be a breaking change, but it could also be pretty easily modified to wrap those SVG elements with a `<text>` that can be descendants of `<text>` per spec.~ 
if you think this change is OK, i'll write some tests for it and then hopefully it could be merged :)
> more flexibility when rendering tick labels with tickFormat

- docs/xy-plot.md
Remove unnecessary blanks and columns.
The last two rows contained two meaningless columns.
> Remove unnecessary columns in the documentation

- docs/label-series.md
- src/plot/series/label-series.js
This is a fix for https://github.com/uber/react-vis/issues/1033
AFAICT (and I'm by no means an SVG expert) alignment-baseline is only supposed to be meaningful relative to a textual parent like a tspan, though chrome accepts it; dominant baseline is the correct attribute to use in this case, as it renders irrespective of the parent.
Alignment Baseline: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
Dominant Baseline: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline
Pre-firefox:
Pre-chrome:
Post-firefox:
Post-chrome:
> Use dominant baseline instead of alignment for consistent rendering

- docs/axes.md
- docs/chart-label.md
- showcase/plot/hexbin-size-example.js
- showcase/plot/line-chart.js
- src/index.js
- src/plot/chart-label.js
- tests/components/hexbin-series-tests.js
- tests/components/line-series-tests.js
- website/src/mdRoutes.js
Sometimes the title prop on the axes component leaves something to be desired, so this PR adds a customizable label that you place where ever:
Before
After
> Construct Chart Label

- showcase/index.js
- showcase/plot/labeled-stacked-vertical-bar-chart.js
- showcase/showcase-sections/plots-showcase.js
- src/utils/series-utils.js
- tests/components/label-series-tests.js
- tests/utils/series-utils-tests.js
Fix stacking together of different Series types.
for example, using this graph from showcase:
https://github.com/uber/react-vis/blob/master/showcase/plot/stacked-vertical-bar-chart.js
Added the last two lines to the showcase example:
```
<XYPlot width={300} height={300} stackBy="y">
<VerticalGridLines />
<HorizontalGridLines />
<XAxis />
<YAxis />
<BarSeries data={[{x: 2, y: 10}, {x: 4, y: 5}, {x: 5, y: 15}]} />
<BarSeries data={[{x: 2, y: 12}, {x: 4, y: 2}, {x: 5, y: 11}]} />
<LabelSeries data={[{x: 2, y: 10, label:"10"}, {x: 4, y: 5, label:"5"}, {x: 5, y: 15, label:"15"}]} />
<LabelSeries data={[{x: 2, y: 12, label:"12"}, {x: 4, y: 2, label:"2"}, {x: 5, y: 11, label:"11"}]} />
```
> Fix stacking together different series types (#1037)

- .travis.yml
Removes a before script from the travis build which was causing it to crash. I don't really know what it does, googling shows this https://docs.travis-ci.com/user/gui-and-headless-browsers/ but we don't really use a headless browser to test things? I also added testing for node 8/9 with the intention of turning off 6/7 because they are not longer under long term support (https://nodejs.org/en/about/releases/).
> Fix build travis build

- docs/bar-series.md
Fixes a broken link to `colors.md`. It was missing a closing parenthesis.
> Fix broken link in Bar Series docs

- src/plot/xy-plot.js
- tests/components/xy-plot-tests.js
This pull request allows the onWheel handler to be undefined to avoid registering an active listener when not needed.
In the case that the XYPlot is used without an onWheel callback the code was registering a listener anyway. This would cause warnings in the chrome console about registering an active listener.
The warning will still be shown in the case that an onWheel callback is set, but this change prevents the listener from being registered when it is a no-op anyway.
> Avoid registering onWheel listener when not needed in XYPlot

- src/radial-chart/index.js
Fix `RadialChart` margin prop to cascade to `ZYPlot` props.
> default to user supplied margins over defaults

- package-lock.json
- package.json
fix #1128 
It also removes a `npm` warning
```
npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
```
> remove unused dependency hoek

- packages/react-vis/src/animation.js
The spread operation was the last item, so it would actually override what it previously set.
> Fix spread

- packages/showcase/examples/force-directed-graph/force-directed-example.js
- packages/showcase/examples/force-directed-graph/force-directed-graph.js
- packages/showcase/examples/responsive-vis/responsive-bar-chart.js
- packages/showcase/examples/responsive-vis/responsive-scatterplot.js
- packages/showcase/examples/responsive-vis/responsive-vis-example.js
- packages/showcase/sunbursts/clock-example.js
This converts the showcase examples listed in #1335 to use hooks. This is slightly in conflict with #1343 which addresses those same examples, although it does so via replacing componentWillRecieve with componentWillUpdate.
> Update problematic showcase examples to use hooks

- packages/react-vis/src/make-vis-flexible.js
- packages/showcase/showcase-sections/misc-showcase.js
Flexible chart doesn't retrieve size information without triggering resize event, causing issue in initial load. Fixing the bug.
This bug was not published in v1.11.7 but was caused by a migration happening post v1.11.7
> Fix flexible chart during initial load

- packages/react-vis/package.json
- packages/react-vis/src/animation.js
- packages/react-vis/src/plot/xy-plot.js
- packages/showcase/package.json
Attempt to upgrade to React 17 https://github.com/uber/react-vis/issues/1356
> Upgrade to React 17
