uber/react-vis

src/lib/utils/scales-utils.js
- Fixed ordinal scales, treating them differently compared to the linear scales (no domain adjustment, different way to compute distance).
=> Fixed broken ordinal scales.

src/example/main.js, src/example/plot/time-chart.js
Adding time chart as an example of the library usage.
=> Add time series as an example

src/test/components.js, src/test/scales-utils.js
- Make sure that the proper functor is returned when no data is passed.
- Fix the failures of XYPlot tests.
@uber-common/data-visualization , please take a look
=> Fix unit tests

src/lib/radial-chart/radial-chart.js
- Added click/mouseover/mouseout interactions for the sections of the radial chart.
- `_arc` is now a property of the radial chart.
This PR duplicates #53 but without merge issues.
@uber-common/data-visualization , please take a look
=> Mouse interactions for the sections of the radial chart.

docs/xy-plot.md, src/lib/plot/series/line-series.js
added the strokeWidth property to lineSeries, so not all lines have to be the same width
=> added the optional strokeWidth property in line series and in docs

src/lib/plot/axis.js
=> Add the supplied class name for the <g> element of the axis

src/test/components.js
- Added the checks for the properties that are set to the components.
- Added the event listeners to the test properties as well.
=> Check all properties in tests

src/example/main.js, src/example/plot/stacked-bar-chart.js, src/lib/plot/xy-plot.js, src/test/index.js, src/test/xy-plot.js
=> Add stacked chart example

src/example/plot/bar-chart.js, src/lib/utils/scales-utils.js
- Update example to include example of bar chart with ordinal scale
Fixes #105
=> fix rendering of bar charts with ordinal scales

src/lib/radial-chart/radial-chart.js
Travis builds are now failing due to an old problem (introduced several months ago). This PR is fixing the issue.
=> Fix failing Travis

docs/xy-plot.md
- Fix link to `Hint` component
- Fix value of style attribute
=> Fix typos and link in xy-plot.md

docs/xy-plot.md
- Add documentation for `onValueClick` and `onSeriesClick events with was introduced in [v0.4](https://github.com/uber/react-vis/blob/master/README.md#04)
=> Update xy-plot.md with click events

src/lib/plot/grid-lines.js
Added missing animation to grid lines (both vertical and horizontal)
This PR fixes #137
=> Add missing animation to grid lines

docs/xy-plot.md, src/example/main.js, src/example/plot/axis-with-turned-labels.js, src/example/plot/custom-axes-orientation.js, src/lib/plot/axis/axis-ticks.js, src/lib/plot/axis/axis-title.js, src/lib/plot/axis/axis.js
- The new `tickLabelAngle` property was added: it's responsible for the angle of the label for the tick mark.
- Fixed the misaligned axis title (#146).
=> Add the support tickAngle property

src/lib/radial-chart/radial-chart.js
Previously section handlers on the radial chart were broken. This change fixes the existing problem
This PR fixes #150
=> Fix the broken section handlers

src/lib/legends/searchable-discrete-color-legend.js
Reported by @javidhsueh
Would prefer adding tests, but would like to unblock some use cases now.
=> Fix legends broken after using Number items

src/lib/utils/animation-utils.js
=> Allow boolean values for Animation PropType

docs/scales-and-data.md, src/example/radial-chart/simple-radial-chart.js, src/lib/utils/scales-utils.js, src/test/scales-utils.js
Introduce a literal scale so that properties can be set specified precisely in the data
=> Add literal scale

docs/scales-and-data.md
=> Update the d3 links in the docs to v4

src/example/plot/area-chart.js, src/example/plot/bar-chart.js, src/example/plot/heatmap-chart.js, src/example/plot/line-chart.js, src/example/plot/linemark-chart.js, src/example/plot/scatterplot.js, src/lib/plot/series/abstract-series.js, src/lib/plot/series/area-series.js, src/lib/plot/series/bar-series.js, src/lib/plot/series/heatmap-series.js, src/lib/plot/series/line-series.js, src/lib/plot/series/mark-series.js, src/lib/radial-chart/radial-chart.js
=> Add className prop to series

src/example/main.js, src/example/plot/area-chart-elevated.js
=> Add example of area chart using y0

src/example/main.scss, src/example/treemap/d3-flare-example.json, src/example/treemap/simple-treemap.js, src/lib/treemap/treemap.js, src/styles/treemap.scss
It turns out the the current tree map does support nested children! However this is unfortunately unclear from the examples so I expanded the base one to be based on bostock's default data set. #153
=> Expand tree example

src/example/plot/area-chart.js, src/lib/plot/series/area-series.js
Following up on noble the work of @skastel, add custom curves to area series also
=> Add custom curves to area charts

src/index.js
Added AbstractSeries to the list of exported classes. Now others can make their own custom series easily.
=> Export AbstractSeries

src/lib/plot/xy-plot.js
Behaves in the same manner as onMouseMove, calling any series components that handle `onParentMouseDown`.
=> Added onMouseDown event to xy-plot

src/example/main.js
Prevents example from running locally.
=> Remove non-existent file import in example/main.js

README.md
Put in the v0.8.0 changelog info into the top-level README.md
=> Add in v0.8.0 changelog information.

src/example/plot/area-chart-elevated.js, src/lib/plot/series/area-series.js, src/lib/plot/series/line-series.js
=> Ensure opacity equals zero is interpreted 0 and not falsy

src/example/radial-chart/simple-radial-chart.js, src/lib/radial-chart/radial-chart.js
=> Demand pie chart actually be in the center

package.json, src/lib/table/table.js, src/lib/utils/react-utils.js, src/lib/utils/scales-utils.js
=> Start warning about the imminent depreciation of the table

docs/sankey.md, package.json, showcase/index.js, showcase/sankey/basic.js, src/index.js, src/sankey/index.js
Demo is quite basic, wanted to keep it clean. I'll create more once I figure how to do interactions correctly.
=> Add basic Sankey diagram

.eslintrc, showcase/treemap/dynamic-treemap.js, src/treemap/index.js, src/utils/scales-utils.js, tests/components.js, tests/scales-utils.js
This PR addresses the feature enhancement from #174, open to other apis, but I feel like this one matches the the other charts reasonable well while providing access to the full node tree.
=> Add interaction listeners for treemap

docs/tutorials/getting-started.md
Here's an initial demo of the getting started guide. Although its not finished, I would like some early reviews so that I can get an idea for that the rest of the docs should look like
=> Initial docs 'getting started guide'

examples/candlestick/README.md, examples/candlestick/app.js, examples/candlestick/candlestick-example.js, examples/candlestick/candlestick.js, examples/candlestick/candlestick.scss, examples/candlestick/index.html, examples/candlestick/node_modules, examples/candlestick/package.json, examples/candlestick/webpack.config.js, examples/candlestick/yarn.lock, examples/complex-chart/complex-chart-example.js, src/styles/examples.scss
This PR exemplifies how to build a custom series and then deploy it! It also addresses our need for better documentation (#210). Here's a gussied up picture:
=> Build an example of building a custom Candlestick visualization

showcase/index.js, showcase/plot/voronoi-line-chart.js, showcase/sankey/voronoi.js, src/index.js, src/plot/voronoi.js, src/sankey/index.js
=> Voronoi component

showcase/plot/complex-chart.js, showcase/treemap/dynamic-treemap.js, src/treemap/index.js, src/treemap/treemap-leaf.js
Pull out a notion of leaf from the treemap to allow for manipulation of the leaves individually!
=> Remodel treemap to allow for animation

docs/radial-chart.md, docs/xy-plot.md, src/legends/continuous-color-legend.js, src/legends/continuous-size-legend.js, src/legends/searchable-discrete-color-legend.js, src/plot/xy-plot.js, src/radial-chart/index.js, src/treemap/index.js
First cut, this follows discussion in #73.
Not sure if updating docs to add `className` entries for the API is really necessary? Happy to discuss 😄
=> Add className prop to top level components.

showcase/plot/custom-axis.js, src/plot/axis/axis.js
=> Allow ticks and line from the axis to be hidden

docs/docs-app/constants/pages.js, examples/streamgraph/README.md, examples/streamgraph/app.js, examples/streamgraph/index.html, examples/streamgraph/node_modules, examples/streamgraph/package.json, examples/streamgraph/streamgraph-example.js, examples/streamgraph/streamgraph-example.scss, examples/streamgraph/webpack.config.js, examples/streamgraph/yarn.lock
Adding another example so that our examples section doesn't look quite so spare
=> Streamgraph example

docs/docs-app/constants/pages.js, docs/markdown/bar-series.md, docs/markdown/heatmap-series.md, docs/markdown/series.md, docs/markdown/xy-plot.md
=> First draft of Bar Series Docs

src/plot/axis/axis-title.js
=> Modified `AxisTitle` to use attribute transform instead of css transform

docs/markdown/xy-plot.md
=> Add note about ordering in the xyplot

showcase/plot/scatterplot.js, src/plot/series/mark-series.js
Make sure to mention strokeWidth as a series prop in #332. This addresses #331
=> Add strokeWidth as a prop to markseries

README.md
Getting my 1-line open source cred in, just updates README to reflect proper npm script for developing locally.
=> Update README to use correct npm script for development

docs/docs-app/actions/index.js, docs/docs-app/components/documentation-page.js, docs/docs-app/components/example-page.js, docs/docs-app/components/layout.js
=> Make docs app faster by only loading one markdown file at a time

docs/docs-app/constants/pages.js, docs/markdown/examples/building-things-other-than-charts.md, docs/markdown/examples/complex-chart.md, docs/markdown/examples/extensibility.md, docs/markdown/examples/responsive-vis.md, docs/markdown/examples/showcase.md, docs/markdown/examples/stream-graph.md
=> Include links to source code in examples

docs/markdown/grids.md
=> Add docs for circular grid lines

docs/markdown/arc-series.md, showcase/index.js, showcase/showcase-app.js, showcase/sunbursts/basic-sunburst.js, showcase/sunbursts/clock-example.js, src/styles/examples.scss
This example constructs another example of how to use the arc series, which can often be a little thorny. This pretty silly example also provides another instance of how to made non-charts using the charting lib.
=> Add additional example for arc series

docs/docs-app/components/home.js
=> Correct home.js typos

CHANGELOG.md, README.md
=> Move breaking changes to changelog

docs/markdown/axes.md, showcase/index.js, showcase/plot/custom-axes.js, showcase/showcase-sections/axes-showcase.js
=> Make a even more comprehensive custom axes example

docs/markdown/axes.md
=> Remove pre 1.0 API reference in axes.md

showcase/sunbursts/basic-sunburst.js
=> Basic sunburst example was using the wrong type of listener

package.json, src/radial-chart/index.js, src/sunburst/index.js, src/utils/chart-utils.js, tests/utils/chart-utils-tests.js, yarn.lock
=> Adjust the margin to center the sunburst chart

.gitattributes, package.json, tests/utils/axis-utils-tests.js, yarn.lock
Also fix gitattributes :smile:
=> feat(core): allow <script> usage with browserify

package.json
Unlock the version of the deck.gl
=> Compatible with newer deck.gl

docs/docs-app/constants/pages.js, docs/markdown/gradients.md, showcase/index.js, showcase/misc/gradient-example.js, showcase/misc/triangle-example.js, showcase/showcase-sections/misc-showcase.js, src/index.js, src/plot/gradient-defs.js, tests/components/gradient-tests.js, yarn.lock
=> Add support for gradients inside of xyplot

docs/webpack.config.js
Webpack 2.3.0 broke the docs gen script, this fixes it
=> Fix docs script

showcase/index.js, showcase/plot/histogram.js, showcase/showcase-sections/plots-showcase.js, tests/components/rect-series-tests.js
This PR adds an example of a more complex histogram, addresses a hole in the examples raised by #426
=> More expansive histogram example

docs/docs-app/constants/pages.js, docs/markdown/examples/zoomable-chart.md, examples/zoomable-chart/README.md, examples/zoomable-chart/app.js, examples/zoomable-chart/highlight.js, examples/zoomable-chart/index.html, examples/zoomable-chart/node_modules, examples/zoomable-chart/package.json, examples/zoomable-chart/webpack.config.js, examples/zoomable-chart/yarn.lock, examples/zoomable-chart/zoomable-chart-example.js, src/styles/examples.scss
An example of an interactive `Highlight` component. On mouse up, the chart then zooms to the specified domain.
This gives an idea of how to make a custom `Series` and leverage the mouse events provided by the  plot.
=> Zoom component

src/plot/axis/axis-title.js, tests/components/axis-title-tests.js, tests/index.js
=> Fix style assignment error by removing spread in AxisTitle

src/utils/scales-utils.js, tests/utils/scales-utils-tests.js
=> Fix VerticalRectSeries - single time slice expands xDomain

showcase/plot/scatterplot.js, src/utils/scales-utils.js, tests/utils/axis-utils-tests.js, tests/utils/scales-utils-tests.js
this is re https://github.com/uber/react-vis/issues/397
=> fixed opacity behavior, added tests

docs/docs-app/constants/pages.js, docs/markdown/colors.md, docs/package.json, docs/yarn.lock, examples/package.json, examples/yarn.lock, package.json, showcase/color/mini-color-examples.js, showcase/index.js, yarn.lock
Pretty long / hopefully comprehensive document about all the ways to use color in react-vis. 
When I started really embracing react-vis getting colors right was my main pain point. Let's hope that this will help others gain full control of color. 
This also highlights a few quirks / inconsistencies of react-vis when it comes to color, so there's more to do on that front. 
Chosen bits - 
---
=> Color documentation

src/index.js
Forgot to export the radar chart from the root
=> Export Radar Chart

package.json, showcase/color/mini-color-examples.js, showcase/treemap/dynamic-treemap.js, tests/components/arc-series-tests.js, tests/components/color-article-tests.js, tests/components/radar-chart-tests.js, tests/components/treemap-tests.js, tests/index.js
This adds tests for @jckr's color article, and a couple of other small things
=> Add a whole bunch of tests

src/utils/scales-utils.js, tests/utils/scales-utils-tests.js
This PR is a copy of c440565495a0caee0d64955f5448002fc3f5816f, the changes were accidentally reverted while trying to fix a bad package. Assigning @sandiiarov as a 'psuedo' reviewer as you were the original author.
=> Re-revert changes w/ VerticalRectSeries

docs/docs-app/constants/pages.js, docs/markdown/flexible-plots.md, showcase/flexible/flexible-examples.js, showcase/index.js, src/index.js, src/make-vis-flexible.js, tests/components/xy-plot-tests.js
addresses https://github.com/uber/react-vis/issues/455
=> make height flexible and vis flexible added

docs/markdown/interaction.md
Fixes https://github.com/uber/react-vis/issues/511
=> Fix an event name typo in the Interaction docs

docs/markdown/crosshair.md
Fixes https://github.com/uber/react-vis/issues/513
=> Fix param name in the Crosshair documentation

src/plot/borders.js, src/plot/gradient-defs.js, src/plot/series/arc-series.js, src/plot/series/line-series.js, src/sunburst/index.js, tests/components/axes-tests.js, tests/components/radial-tests.js, tests/components/sunburst-tests.js
This also adds smart defaults for the sunburst's arcs as requested in #483
=> Change class="undefined" to class=" "

docs/markdown/arc-series.md, docs/markdown/bar-series.md, docs/markdown/interaction.md, docs/markdown/line-mark-series.md, docs/markdown/mark-series.md
=> correct docs typos

showcase/radar-chart/animated-radar-chart.js, src/utils/axis-utils.js, tests/components/radar-chart-tests.js, tests/utils/axis-utils-tests.js
=> Decorative Slope generation incorrect when slope is vertical

docs/markdown/legends.md, showcase/legends/horizontal-discrete-custom-palette.js, showcase/showcase-sections/legends-showcase.js, src/legends/discrete-color-legend-item.js, src/legends/discrete-color-legend.js, tests/components/legends-tests.js
This PR is a continuation of #526 it adds tests to address the functionality suggested by @murilobast  and refactors discrete legend to be more in line with the current style. Finally it also adds the ability to specify elements in the discrete legend.
=> Implementing mouse Enter and Leave events on DiscreteColorLegend component v2

docs/package.json, docs/webpack.config.js, docs/yarn.lock, src/styles/examples.scss
=> Use prod version of react and minify bundle

docs/docs-app/constants/pages.js, docs/markdown/whisker-series.md, showcase/index.js, showcase/plot/whisker-chart.js, showcase/showcase-sections/plots-showcase.js, src/index.js, src/plot/series/whisker-series.js, tests/components/whisker-series-tests.js, tests/index.js
Addresses the first half of https://github.com/uber/react-vis/issues/521.
=> Add a Whisker series type for plotting variance

docs/markdown/examples/extensibility.md
Fixes https://github.com/uber/react-vis/issues/555
=> Fix the Candlestick example source code link

docs/markdown/scales-and-data.md, docs/markdown/sunburst.md
Addresses https://stackoverflow.com/questions/45703136/how-to-enable-tooltip-on-react-vis and #527
=> Sunburst & Reverse docs

markdown/examples/zoomable-chart.md
Link for zoomable chart was broken
=> update broken link in github pages

docs/markdown/sunburst.md, showcase/sunbursts/sunburst-with-tooltips.js, src/sunburst/index.js, tests/components/sunburst-tests.js
=> Enable rotation on the labels of sunburst

showcase/examples/dragable-chart/drag-marker.js, showcase/examples/dragable-chart/dragable-chart-example.js, showcase/showcase-app.js, showcase/showcase-index.js, src/plot/voronoi.js, tests/components/dragable-chart-tests.js, tests/index.js
This PR adds mouseUp and mouseDown events, which make it much easier to implement dragging on the Voronoi componont.
I didn't see any tests for the Voronoi component, so not sure what style of test this enhancement would benefit from (if any).
=> Voronoi: Add mouseUp and mouseDown events

showcase/index.js, showcase/plot/bar-chart.js, showcase/plot/big-base-bar-chart.js, showcase/showcase-sections/plots-showcase.js, src/plot/xy-plot.js, tests/components/bar-series-tests.js, tests/components/rect-series-tests.js
As highlighted in #573 it is really confusing that baseValue takes over an inserts itself into different series behaviour. This PR modifies baseValue so that if the user specifies a domain, the base value is equal to the bottom of that domain. 
There is some mess, in that this PR also has #580 in it, though as soon as that lands this can be clean up too.
=> Make baseValue copy domain

docs/markdown/xy-plot.md, src/plot/xy-plot.js
Adds onClick, onDoubleClick and onWheel event handlers.
=> XYPlot: add support for various mouse events

docs/markdown/crosshair.md, src/plot/crosshair.js
I can do the same for the line width, if that makes sense.
=> Crosshair: allow to specify styles in props

docs/flexible-plots.md
Fix typo in FlexibleXYPlot documentation
=> Fix typo in FlexibleXYPlot closing bracket

docs/presentation.md, package.json, showcase/axes/axis-on-0.js, showcase/index.js, showcase/showcase-sections/axes-showcase.js, src/plot/axis/axis.js, src/plot/axis/y-axis.js, src/utils/axis-utils.js, tests/components/axes-tests.js
Addresses https://github.com/uber/react-vis/issues/623
=> adds possibility to set axis on 0 vs on edge of chart

docs/area-series.md, docs/line-mark-series.md, docs/line-series.md, showcase/misc/null-data-example.js, src/plot/series/area-series.js, src/plot/series/line-series.js, src/plot/series/mark-series.js, tests/components/line-series-tests.js
=> Rename nullAccessor to getNull

docs/voronoi.md, src/plot/voronoi.js, tests/components/voronoi-tests.js, tests/index.js, website/src/mdRoutes.js
Closes #684
This change makes it possible to conditionally add classnames and styles to Voronoi cell, depending on the data points.
This PR also adds initial docs for the Voronoi diagram.
=> Add classname and styles to Voronoi cells

src/legends/discrete-color-legend.js, tests/components/legends-tests.js
=> Fix bug #647 - Legend Items are always "clickable"

showcase/showcase-links.js
=> Fix radar links

showcase/showcase-links.js
=> Add links to legends

docs/radial-chart.md, showcase/radial-chart/simple-radial-chart.js, src/plot/series/label-series.js, src/radial-chart/index.js
A couple of changes to radial-charts for consistency. Now labels won't HAVE to be 12px. 
Addresses #705
=> changes to the radial chart api to pass styles for labels

package.json
previous version could create issues with flow
=> bump react motion to 0.5.2

package.json
=> bump peer dependency of react to 15.3 since were using pureComponents

website/src/config.js, website/yarn.lock
=> Ga tracker

docs/label-series.md, src/plot/series/label-series.js
Added labelAnchorX and labelAnchorY props for label-series.
- **labelAnchorX**: Value of this prop will be used as textAnchor attribute for the <text> element. If it is not provided, the textAnchor will be calculated and set automatically depending on the label position (= as it has been set and calculated always until now)
- **labelAnchorY**: Value of this prop will be used as alignmentBaseline attribute for the <text> element. If it is not provided, the alignmentBaseline will be calculated and set automatically depending on the label position (= as it has been set and calculated always until now)
So basically these props enable user to manually set that for example label is always on the top and middle of the datapoint.
E.g. if we set labelAnchorX="middle" and …
=> Add ability to manually set label text alignment for label-series.

docs/examples/zoomable-chart.md
- Fixed URL of the [zoomable chart](https://github.com/uber/react-vis/blob/master/showcase/examples/zoomable-chart/zoomable-chart-example.js)
=> fix(docs): Fix source code link of zoomable chart

docs/line-mark-series.md
Instead of doing
style={{line: {stroke:"blue"}, mark: {stroke:"red"}}}
styling lines and marks separately should look like
lineStyle={{stroke:"red"}}
markStyle={{stroke:"blue"}}
=> Styling LineMarkSeries

docs/hint.md
The "orientation" prop should've been "align", and should be an Object type.
=> Correct doc hint.md; "orientation" --> "align"

showcase/showcase-links.js
- fixed source code URL of turned axis labels
Resolves #828
=> fix(docs): Fixed source code URL of turned axis labels

docs/xy-plot.md
- Fixed broken links in `xy-plot`
- Fixed a typo in code snippet
=> fix(docs): Fixed broken links and typo in XY-Plot

package-lock.json, showcase/package-lock.json, src/styles/plot.scss
=> Removes duplicate line styles (#786)

showcase/index.js, showcase/radar-chart/four-quadrant-radar-chart.js, showcase/showcase-links.js, showcase/showcase-sections/radar-showcase.js, tests/components/radar-chart-tests.js, tests/utils/axis-utils-tests.js
These tests are a follow up to issue #796 and pull request #842 .
=> Adds additional tests to radar chart

docs/gradients.md, showcase/index.js, showcase/radial-chart/gradient-pie.js, showcase/showcase-links.js, showcase/showcase-sections/radial-showcase.js, tests/components/radial-tests.js
=> Add an example of using gradients in radial charts

website/src/mdRoutes.js
Also alphabetized that section of the docs
=> Parallel coordinates docs weren't showing in other charts

docs/arc-series.md
=> Add radius domain to the arc series docs

docs/parallel-coordinates.md, showcase/parallel-coordinates/basic-parallel-coordinates.js, src/parallel-coordinates/index.js
=> enable styling individual lines in paralell coordinates

docs/sankey.md, showcase/sankey/basic.js, src/sankey/index.js
=> Enable rotation of sankey labels

src/plot/series/canvas-wrapper.js
=> canvas arguments out of order

docs/colors.md
=> Address typo in color series

docs/mark-series.md, docs/voronoi.md, showcase/axes/dynamic-crosshair-scatterplot.js, tests/components/voronoi-tests.js
My previous pr on the topic of voronoi plus markseries (#897) failed to recognize that an example already kinda existed. I've improved the previous example to do what it's name claimed it does and recreated the changes that were valuable from my previous PR.
=> Scatterplot already exisits

showcase/sankey/voronoi.js, tests/components/sankey-tests.js
=> Show an example of changing Sankey names dynamically

showcase/index.js, showcase/plot/bar-chart.js, showcase/plot/line-series-canvas-nearest-xy-example.js, showcase/showcase-sections/plots-showcase.js, tests/components/bar-series-tests.js
This PR adds an example of label series with ordinal data and improves the labeling of a recent canvas example.
=> Improve some of the examples

docs/mark-series.md, docs/voronoi.md, website/src/mdRoutes.js
=> Docs fixes

docs/xy-plot.md
A Twitter thread showed this wording, and the consensus there was that this was an overly complicated way of phrasing. I simplified that text a bit, it seems just as clear to me (even after looking up what "to wit" means).
=> docs: simplify usage a bit

src/index.js
Take care of Alphabetize TODO.
=> Alphabetize

docs/grids.md, docs/hint.md, docs/style.md, package-lock.json, src/plot/grid-lines.js, src/plot/hint.js, tests/components/grid-lines-tests.js, tests/components/hints-tests.js, tests/index.js
Add `className` prop to `Hint` and `GridLines` components. 
Resolves #1002.
=> Add className functionality to Hint and GridLines

showcase/webpack.config.js
Fixing the build issue on windows, added only to the development webpack
=> fix webpack windows build issue(#940)

docs/rect-series.md
Not sure if there is more to this?
Issue: 937,
Reviewer: PR
=> Correct the rect-series docs for x & x0 to align with the code.

showcase/showcase-links.js
=> Fix link to empty chart

docs/legends.md, showcase/index.js, showcase/legends/searchable-discrete-color-hover.js, showcase/showcase-links.js, showcase/showcase-sections/legends-showcase.js, showcase/yarn.lock, src/legends/searchable-discrete-color-legend.js, tests/components/legends-tests.js
Added ability to utilize props onItemMouseEnter and onItemMouseLeave in SearchableDiscreteColorLegend as referenced in #1112.
I mimic'd the onMouseItemEnter/Leave example from the DiscreteColorLegend: Custom palette with hover interaction example. Added tests for the example and updated documentation.
=> feat(SearchableDiscreteColorLegend): Expose onItemMouseEnter & onItemMouseLeave

package.json, packages/website/.storybook/config.js, packages/website/package.json, packages/website/storybook/areaseries-story.js, packages/website/storybook/axis-story.js, packages/website/storybook/barseries-story.js, packages/website/storybook/index.js, packages/website/storybook/legend-story.js, packages/website/storybook/lineseries-story.js, packages/website/storybook/markseries-story.js, packages/website/storybook/radial-story.js, packages/website/storybook/storybook-utils.js, packages/website/webpack.config.js, yarn.lock
Added the website to the list of packages, and got the storybook working.
Upgraded the required packages, and fix the storybooks to work with the new versions.
=> Get Storybook working.

package.json, packages/react-vis/package.json, packages/showcase/package.json, packages/website/package.json, yarn.lock
Update pre-commit script to run the remove-unpm-rfs script
=> Use react@^16.8.3 as minimum

packages/showcase/webpack.config.js, packages/website/package.json, packages/website/webpack.config.js
=> Add babel options to website

.eslintrc, .prettierrc, package.json, packages/react-vis/package.json, yarn.lock
Move the exlude patterns to .eslint
=> Don't lint the dist/ and es/ folders

docs/treemap.md
first off, thanks for this awesome lib!
I was going through the Treemap docs and came across the broken link so I fixed it :) 
cheers! 🍻
=> fix broken link in treemap docs

docs/examples/building-things-other-than-charts.md, docs/examples/extensibility.md, docs/examples/iris-dashboard.md, docs/examples/responsive-vis.md, docs/examples/stream-graph.md, docs/sunburst.md, packages/showcase/showcase-links.js, packages/showcase/showcase-sections/misc-showcase.js, packages/showcase/showcase-sections/parallel-coordinates-showcase.js, packages/showcase/showcase-sections/plots-showcase.js, packages/showcase/showcase-sections/radar-showcase.js, packages/showcase/showcase-sections/radial-showcase.js, packages/showcase/showcase-sections/sankeys-showcase.js, packages/showcase/showcase-sections/sunburst-showcase.js, packages/showcase/showcase-sections/treemap-showcase.js
=> Fix docs and showcase links with the new packages structure

.eslintrc, package.json, packages/react-vis/src/make-vis-flexible.js, packages/react-vis/src/treemap/index.js, packages/showcase/showcase-links.js, yarn.lock
=> Migrate Treemap and makeFlexible to functional components

README.md
I completely missed the warning & built a new component based on this library this week.
=> add more clear deprecation warning

package.json, packages/react-vis/package.json, yarn.lock
Once we make upgrade to all other d3-* libraries, and upgrade ocular, we can remove the resolution.
=> adding yarn resolution to d3-color and fix build script 

publish.sh
Example command
```
./publish.sh -v 2.0.1-alpha.0 --tag alpha --dry-run
```
=> add publish script

packages/website/package.json
User could create the package with the same name in the repository.
=> Fix a potential security bug
